import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF003B5D);
const Color onPrimaryColor = Color(0xFFE5E7EB);
const Color secondaryColor = Color(0xFF34AADC);
const Color backgroundColor = Color(0xFFF5F7FA);
const Color onBackgroundColor = Color(0xFF1F2937);
const Color textColor = Color(0xFF333333);
const Color blackColor = Color(0xFF1F2937);
const Color whiteColor = Color(0xFFFFFFFF);
const Color errorColor = Color.fromARGB(255, 206, 49, 49);
const Color inProgressColor = Color(0xFFDCFCE7);
const Color onInProgressColor = Color(0xFF16A34A);
const Color onHoldColor = Color(0xFFE5E7EB);
const Color onOnHoldColor = Color(0xFF1F2937);
const Color pendingColor = Color(0xFFFFEDD5);
const Color onPendingColor = Color(0xFFEA580C);
const Color finishedColor = Color(0xFFEFF6FF);
const Color onFinishedColor = Color(0xFF2563EB);
const Color unselectedButtonNavbarColor = Color(0xFF9CA3AF);
const Color lightGreyColor = Color(0xFFCCCCCC);
const Color borderLightGreyColor = Color(0xFFF3F4F6);
const Color mediumGreyColor = Color(0xFF9CA3AF);
const Color greyTextColor = Color(0xFF6B7280);
const Color lightBlue = Color(0xFFEFF6FF);
const Color onLightBlue = Color(0xFF2563EB);
const Color redTextColor = Color(0xFFEF4444);
const Color orangeColor = Color(0xFFFFA500);

const Color greenButtonColor = Color(0xFF10B981);
const Color redButtonColor = Color(0xFFF87171);
